//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/UI_Master/Resources/InputSystem/UIMControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @UIMControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @UIMControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""UIMControls"",
    ""maps"": [
        {
            ""name"": ""UI"",
            ""id"": ""10378d1e-4d78-4563-b3c4-990353855967"",
            ""actions"": [
                {
                    ""name"": ""CallGold"",
                    ""type"": ""Button"",
                    ""id"": ""4cdf4783-0fa4-437c-9db2-4fef10c5010f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""32703407-f914-4480-bfad-ce5d5984bc5e"",
                    ""path"": ""<Keyboard>/f11"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CallGold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""KEYBOARD"",
            ""bindingGroup"": ""KEYBOARD"",
            ""devices"": []
        }
    ]
}");
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_CallGold = m_UI.FindAction("CallGold", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // UI
    private readonly InputActionMap m_UI;
    private IUIActions m_UIActionsCallbackInterface;
    private readonly InputAction m_UI_CallGold;
    public struct UIActions
    {
        private @UIMControls m_Wrapper;
        public UIActions(@UIMControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @CallGold => m_Wrapper.m_UI_CallGold;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void SetCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterface != null)
            {
                @CallGold.started -= m_Wrapper.m_UIActionsCallbackInterface.OnCallGold;
                @CallGold.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnCallGold;
                @CallGold.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnCallGold;
            }
            m_Wrapper.m_UIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @CallGold.started += instance.OnCallGold;
                @CallGold.performed += instance.OnCallGold;
                @CallGold.canceled += instance.OnCallGold;
            }
        }
    }
    public UIActions @UI => new UIActions(this);
    private int m_KEYBOARDSchemeIndex = -1;
    public InputControlScheme KEYBOARDScheme
    {
        get
        {
            if (m_KEYBOARDSchemeIndex == -1) m_KEYBOARDSchemeIndex = asset.FindControlSchemeIndex("KEYBOARD");
            return asset.controlSchemes[m_KEYBOARDSchemeIndex];
        }
    }
    public interface IUIActions
    {
        void OnCallGold(InputAction.CallbackContext context);
    }
}
